name: tv_maze
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #Design System
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.4
  flex_color_scheme: ^6.1.2
  cached_network_image: ^3.2.3
  flutter_staggered_grid_view: ^0.6.2
  

  #System
  flutter_modular: ^5.0.3
  logger: ^1.1.0
  visibility_detector: ^0.3.3
  overlay_support: ^2.1.0
  result_dart: ^1.0.3
  intl_utils: ^2.4.1

  #HTTP
  dio: ^4.0.6

  #Tests
  mocktail: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "lib/app/design/assets/logo.png"


flutter:
  uses-material-design: true

  assets:
    - lib/app/design/assets/

flutter_intl:
  enabled: true
  main_locale: en
  arb_dir: lib/core/l10n
  output_dir: lib/core/l10n 
