name: tv_maze
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #Design System
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.4
  flex_color_scheme: ^6.1.2

  #System
  flutter_modular: ^5.0.3
  logger: ^1.1.0
  visibility_detector: ^0.3.3
  overlay_support: ^2.1.0
  result_dart: ^1.0.3

  #HTTP
  dio: ^4.0.6

  #Tests
  mocktail: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  # assets:
  #   -

flutter_intl:
  enabled: true
  main_locale: en
  arb_dir: lib/core/l10n
  output_dir: lib/core/l10n 
